In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
import os

In [5]:
os.getcwd()

'c:\\Users\\Meghan\\DSI_Foundations\\Module2_Python\\python\\.github'

In [16]:
os.chdir("c:\\Users\\Meghan\\DSI_Foundations\\Module2_Python\\python\\02_activities\\assignments")

In [20]:
os.getcwd()

'c:\\Users\\Meghan\\DSI_Foundations\\Module2_Python\\python\\02_activities\\assignments'

In [28]:
all_paths = [
  "../../05_src/data/assignment_2_data/inflammation_01.csv",
  "../../05_src/data/assignment_2_data/inflammation_02.csv",
  "../../05_src/data/assignment_2_data/inflammation_03.csv",
  "../../05_src/data/assignment_2_data/inflammation_04.csv",
  "../../05_src/data/assignment_2_data/inflammation_05.csv",
  "../../05_src/data/assignment_2_data/inflammation_06.csv",
  "../../05_src/data/assignment_2_data/inflammation_07.csv",
  "../../05_src/data/assignment_2_data/inflammation_08.csv",
  "../../05_src/data/assignment_2_data/inflammation_09.csv",
  "../../05_src/data/assignment_2_data/inflammation_10.csv",
  "../../05_src/data/assignment_2_data/inflammation_11.csv",
  "../../05_src/data/assignment_2_data/inflammation_12.csv"
]

with open(all_paths[0], 'r') as f_01:
    # YOUR CODE HERE: Use the readline() or readlines() method to read the .csv file into a variable
    lines = f_01.readlines() # variable to use for opening lines from file
    # YOUR CODE HERE: Iterate through the variable using a for loop and print each row for inspection
    for line in lines:
      print(line)

0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0

0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1

0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1

0,0,2,0,4,2,2,1,6,7,10,7,9,13,8,8,15,10,10,7,17,4,4,7,6,15,6,4,9,11,3,5,6,3,3,4,2,3,2,1

0,1,1,3,3,1,3,5,2,4,4,7,6,5,3,10,8,10,6,17,9,14,9,7,13,9,12,6,7,7,9,6,3,2,2,4,2,0,1,1

0,0,1,2,2,4,2,1,6,4,7,6,6,9,9,15,4,16,18,12,12,5,18,9,5,3,10,3,12,7,8,4,7,3,5,4,4,3,2,1

0,0,2,2,4,2,2,5,5,8,6,5,11,9,4,13,5,12,10,6,9,17,15,8,9,3,13,7,8,2,8,8,4,2,3,5,4,1,1,1

0,0,1,2,3,1,2,3,5,3,7,8,8,5,10,9,15,11,18,19,20,8,5,13,15,10,6,10,6,7,4,9,3,5,2,5,3,2,2,1

0,0,0,3,1,5,6,5,5,8,2,4,11,12,10,11,9,10,17,11,6,16,12,6,8,14,6,13,10,11,4,6,4,7,6,3,2,1,0,0

0,1,1,2,1,3,5,3,5,8,6,8,12,5,13,6,13,8,16,8,18,15,16,14,12,7,3,8,9,11,2,5,4,5,1,4,1,2,0,0

0,1,0,0,4,3,3,5,5,4,5,8,7,10,13,3,7,13,15,18,8,15,15,16,11,14,12,4,10,10,4,3,4,5,5,3,3,2,2,1

0,1,0,0,3,

In [60]:
data = np.loadtxt("../../05_src/data/assignment_2_data/inflammation_01.csv", delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [73]:
import numpy as np

def patient_summary(file_path, operation):
    data = np.loadtxt(fname=file_path, delimiter=',') # Load the data from the file
    ax = 1  # This specifies that the operation should be done for each row (patient)

    # Implement the specific operation based on the 'operation' argument
    if operation == 'mean':
        print(matrix.mean())
    elif operation == 'max':
        print(matrix.max())
            
    elif operation == 'min':
        print(nmatrix.min())

    else:
        # If the operation is not one of the expected values, raise an error
        raise ValueError("Invalid operation. Please choose 'mean', 'max', or 'min'.")

    return summary_values

In [75]:
patient_summary("../../05_src/data/assignment_2_data/inflammation_01.csv",min)

ValueError: Invalid operation. Please choose 'mean', 'max', or 'min'.